README.md, docs/rules/no-duplicate-imports.md, src/index.js, src/rules/no-duplicate-imports.js, tests/rules/no-duplicate-imports.test.js
-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Add a new `no-duplicate-imports` rule.
- Created `no-duplicate-imports` rule
- Added tests for the rule
- Added docs for the rule
=> feat: Add no-duplicate-imports rule

tests/package/exports.js, tests/plugin/eslint.test.js
-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Ensures that all rules available in `src/rules` are exported in `plugin.rules`. Also adds a test for plugin configs that would fail if, for example, the config enables a non-existent rule.
Added tests.
https://github.com/eslint/json/pull/53
=> test: Ensure all rules are exported

README.md, docs/rules/no-unknown-at-rules.md, src/index.js, src/rules/no-unknown-at-rules.js, src/rules/no-unknown-properties.js, tests/rules/no-unknown-at-rules.test.js
-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Implement the `no-unknown-at-rule` rule
- Implemented `no-unknown-at-rule`
- Added tests
- Added docs
- Added rule as recommended
This is built on top of #5, so we should merge that first.
=> feat: no-unknown-at-rules rule

README.md, eslint.config.js, package.json, src/rules/no-duplicate-imports.js, src/rules/no-empty-blocks.js, src/rules/no-invalid-properties.js, src/rules/no-unknown-at-rules.js
-   [x] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
Enables `eslint-plugin-eslint-plugin` for linting rules and rule tests.
Added `eslint-plugin-eslint-plugin` dev dependency and enabled rules in the eslint config.
Also removed the ending dot from `meta.docs.description` in rules.
Config is the same as in eslint/json repo (https://github.com/eslint/json/pull/64).
=> chore: use eslint-plugin-eslint-plugin

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/ci.yml, docs/rules/no-duplicate-imports.md, docs/rules/no-empty-blocks.md, docs/rules/no-invalid-at-rules.md, docs/rules/no-invalid-properties.md, package.json, src/index.js, src/rules/no-duplicate-imports.js, src/rules/no-empty-blocks.js, src/rules/no-invalid-at-rules.js, src/rules/no-invalid-properties.js, tests/types/tsconfig.json, tests/types/types.test.ts
-   [X] I have read the [contributing guidelines](https://github.com/eslint/eslint/blob/HEAD/CONTRIBUTING.md).
fix types and add type tests
- Refactoring to ensure that the generated `plugin` type includes all relevant properties, especially `plugin.configs.recommended`.
- Added type tests similar to eslint/json#61
- Reformatted Markdown files using Prettier 3.4. Also updated the Prettier version in `package.json`.
eslint/json#52
`.md` files were reformatted by Prettier. See https://prettier.io/blog/2024/11/26/3.4.0#markdown.
=> fix: add type tests

.github/workflows/ci.yml, package.json, tests/types/types.test.ts
Fix the types test.
~~Commented out the test to verify that the plugin satisfies `ESLint.Plugin`. This can't happen because `ESLint.Plugin` rules aren't yet updated to match language plugin rules type.~~
Ensure that `npm run build` is always run before the types test.
=> test: Fix types test

src/rules/no-duplicate-imports.js, src/rules/no-empty-blocks.js, src/rules/no-invalid-at-rules.js, src/rules/no-invalid-properties.js
Improve the DX, particularly because many people expect eslint to only lint JS files. So making the docs easily accessible is important.
Add [`docs.url`](https://eslint.org/docs/latest/extend/custom-rules#url) to every rule, so that you can click on the rule in your IDE to go directly to the documentation
&shy;-
&shy;-
=> chore: add link to docs in each eslint rule

README.md, package.json, src/languages/css-language.js, tests/languages/css-language.test.js, tests/plugin/eslint.test.js
Add a tolerant parsing mode.
- Updated `CSSLanguage` to contain `defaultLanguageOptions` and `validateLanguageOptions()`
- Updated `CSSLanguage#parse()` to accept language options
- Updated tests
- Upgraded `@eslint/core` to v0.7.0 (not the latest, for best compatibility)
fixes #29
=> feat: Add tolerant parsing mode

docs/rules/no-invalid-properties.md, src/rules/no-invalid-properties.js, tests/rules/no-invalid-properties.test.js
Ensure that property values with `var(...)` don't throw an error in `no-invalid-properties`.
- Catch `var() not supported` errors from CSS Tree and don't display to the user in `no-invalid-properties`
- Updated documentation for `no-invalid-properties`
- Added a test
refs #40
This isn't really a fix for the issue, just suppressing the error for now. This needs to be fixed upstream in CSSTree for a better fix:
https://github.com/csstree/csstree/issues/317
=> fix: Suppress var() validation errors

.github/workflows/ci-build-all-pm.yml
Current CI checks do not include checking that the packaged version of the repo can be installed. This has allowed release of versions with installation regressions.
This PR adds a new workflow `ci-build-all-pm.yml` that fills the gap of checking the ability to install.
A tarball is created from the repo package source using [npm pack](https://docs.npmjs.com/cli/v11/commands/npm-pack).
The tarball `eslint-css-<version>.tgz` is then used to install with each of the package manager instructions listed in the [README > Installation](https://github.com/eslint/css/blob/main/README.md#installation) section
```shell
npm install @eslint/css -D
yarn add @eslint/css -D
pnpm install @eslint/css -D
bun install @eslint/css -D
```
For Yarn, both [Yarn v1 Classic](https://classic.yarnpkg.com/) and [Yarn …
=> ci: add package manager install checks

docs/rules/require-baseline.md, src/rules/require-baseline.js, tests/rules/require-baseline.test.js
Add support for validating the Baseline status of selectors like `:has()`
- added a new `Selector` handler that checks the validity of all child nodes
- added tests for pseudo-class and pseudo-element selectors
- updated docs
Fixes #60
=> feat: add selector support to require-baseline

README.md
It corrects the non-working Deno installation instruction in the [README > Installation](https://github.com/eslint/css/blob/main/README.md#installation) section.
Installation instruction corrected to read as follows:
```shell
deno add jsr:@eslint/css
```
Deno is marked as experimental.
- closes https://github.com/eslint/css/issues/66
- This duplicates https://github.com/eslint/css/pull/70. Only one of these PRs is needed.
=> docs: add jsr and experimental to Deno command

README.md, docs/rules/prefer-logical-properties.md, src/index.js, src/rules/prefer-logical-properties.js, tests/rules/prefer-logical-properties.test.js
Add new rule.
Added new rule for usage logical CSS properties instead of phisical.
#13
I don't think so.
=> feat: add prefer-logical-properties rule

src/rules/require-baseline.js, tests/rules/require-baseline.test.js
Add support for evaluating baseline support for CSS nesting
- added a test for CSS nesting
- added a handler for the `NestingSelector` key that checks for `nesting` selector availability
- added a check to `isSupported` so unknown feature statuses are supported by default (if the `nesting` ID happens to change, the test will fail and there won't be a runtime error)
fixes #85 
Should the `nesting` selector ID be saved as a constant somewhere, or is it ok to hard-code it in the `NestingSelector` handler?
=> feat: CSS nesting baseline support

docs/rules/use-layers.md, src/rules/use-layers.js, tests/rules/use-layers.test.js
This pull request adds support for period-separated layer names in the `use-layers` rule.  
- Added support for period-separated layer names in the `use-layers` rule.  
- Added tests.
- Updated documentation.
fixes #88
=> fix: Add support period-separated layer names in use-layers rule

src/rules/require-baseline.js, tests/rules/require-baseline.test.js
Fixes incorrect flagging of `highlight` class name in `require-basline`
- Updated `require-baseline` to skip class, type, ID, and attribute selectors
- Added test to verify the change
fixes #91
Ping @rviscomi can you take a look at this to make sure I fixed it correctly?
=> fix: Don't check class names in require-baseline

package.json, src/languages/css-language.js, tests/languages/css-language.test.js
Catches some additional parsing errors
- Added specific error messages for unclosed braces, square brackets, and parentheses (only in strict mode, hidden in tolerant mode)
- Updated tests
- Upgraded `@eslint/css-tree`
-
=> fix: Catch more parse errors

eslint.config.js, src/rules/use-baseline.js
Adds `meta.docs.url` in the `use-baseline` rule.
Added the URL and enabled `eslint-plugin/require-meta-docs-url` rule that would have caught this.
=> docs: Add `use-baseline` URL

docs/rules/use-baseline.md
This change improves the `use-baseline` rule docs by:
* Clarifying what Baseline is and is not, by telling developers that WA features are safer to use, but that testing is still necessary, and by telling them that non-WA features are fine to use.
* Changing a few of the links to point to the WebDX CG site instead of web.dev.
I updated the use-baseline.md file.
refs #80.
N/A
=> docs: Better Baseline comms in use-baseline.md

.github/workflows/ci-build-all-pm.yml
The `yarn-install` job in the workflow [.github/workflows/ci-build-all-pm.yml](https://github.com/eslint/css/blob/main/.github/workflows/ci-build-all-pm.yml) relies on a version of Corepack bundled with Node.js. The Node.js website https://nodejs.org/docs/latest/api/corepack.html states "... Corepack itself will no longer be distributed with future versions of Node.js." which would cause the workflow to break.
[Yarn > Installation](https://yarnpkg.com/getting-started/install) now recommends using
```shell
npm install -g corepack
```
In the workflow [.github/workflows/ci-build-all-pm.yml](https://github.com/eslint/css/blob/main/.github/workflows/ci-build-all-pm.yml), add `npm install -g corepack@latest` before using Corepack in the job `yarn-install`.
Note that although a global install of …
=> ci: use standalone Corepack for Yarn

.github/workflows/ci-build-all-pm.yml
The `pnpm-install` job in the workflow [.github/workflows/ci-build-all-pm.yml](https://github.com/eslint/css/blob/main/.github/workflows/ci-build-all-pm.yml) relies on a version of Corepack bundled with Node.js. The Node.js website https://nodejs.org/docs/latest/api/corepack.html states "... Corepack itself will no longer be distributed with future versions of Node.js." which would cause the workflow to break.
Following the pnpm package manager's documentation [Continuous Integration > GitHub Actions](https://pnpm.io/continuous-integration#github-actions), the installation method for pnpm in GitHub Actions is changed to using the JavaScript GitHub Action [pnpm/action-setup@v4](https://github.com/pnpm/action-setup), replacing the need for Corepack.
In the workflow …
=> ci: use pnpm/action-setup for pnpm

README.md, docs/rules/no-important.md, src/index.js, src/rules/no-important.js, src/util.js, tests/rules/no-important.test.js
This pull request introduces a new rule, `no-important`, which disallows the use of the !important flag in declarations.
- Implemented the no-important rule to detect and warn when !important is used.
- Added documentation for the rule
- Added tests
Closes #20, Closes #23
=> feat: add no-important rule

README.md
Add instructions to the README for setting up CSS linting in VS Code and JetBrains WebStorm.
=> docs: Add instructions for editor setup

src/rules/no-invalid-at-rules.js, tests/rules/no-invalid-at-rules.test.js
This PR modifies the `no-invalid-at-rules` rule to allow custom descriptors in at-rules.
Modified the `no-invalid-at-rules` rule to skip validation for any descriptor that starts with `--`
Closes #127
=> feat: allow custom descriptors in no-invalid-at-rules

README.md, docs/rules/relative-font-units.md, src/index.js, src/rules/relative-font-units.js, tests/rules/relative-font-units.test.js
Add a new rule called `relative-font-units` that will enforce the relative units for font size.
Added the rule `relative-font-units` with an option called `allow` and related tests and docs and updated README.md file.
fixes #73
=> feat: add `relative-font-units` rule

docs/rules/no-important.md, tests/rules/no-important.test.js
This PR addresses issue #146 by documenting that !important declarations within `@keyframes` rules are ignored by browsers. While this case is already caught by the existing no-important rule, the documentation update makes this behavior more explicit and helps developers understand why using !important in keyframes is problematic.
- Updated the no-important rule documentation to explicitly mention that !important declarations within `@keyframes` rules are ignored by browsers
- Added test cases for keyframe !important validation
Fixes #146
=> docs: add keyframe !important documentation

package.json
In this PR, I've updated lint-staged script to use predefined script.
Currently, `node tools/update-rules-docs.js` script is defined in `script` as `npm run build:update-rules-docs`, but it was not used.
=> chore: update lint-staged to use predefined script

src/languages/css-language.js
**Edited**:
In this PR, I've fixed wrong JSDoc directive.
=> chore: fix wrong JSDoc tag

README.md, docs/rules/no-invalid-named-grid-areas.md, src/index.js, src/rules/no-invalid-named-grid-areas.js, tests/rules/no-invalid-named-grid-areas.test.js
This PR adds a new rule `no-invalid-named-grid-areas` to enforce valid named grid area definitions in CSS Grid templates. The rule helps prevent common mistakes when using grid-template-areas and related properties by checking that named grid areas are properly defined according to the CSS Grid specification.
Added the  `no-invalid-named-grid-areas` rule, along with documentation and tests.
Fixes #158
=> feat: add no-invalid-named-grid-areas rule

tsconfig.json
Prevents type errors from being reported when run inside a directory with `node_modules/@types/sizzle`. See: https://github.com/eslint/eslint/pull/19643/files#r2155194866
Enables [`skipLibCheck`](https://aka.ms/tsconfig#skipLibCheck) to prevent type checking of external `.d.ts` files.
* https://github.com/eslint/eslint/pull/19643/files#r2155194866 
* https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73082
=> chore: enable skipLibCheck

package.json, src/types.ts
Simplify type definitions.
* Refactored the type definition of `CSSRuleDefinition` using the core [`CustomRuleDefinitionType`](https://github.com/eslint/rewrite/blob/core-v0.15.0/packages/core/src/types.ts#L598-L631) type.
* Redefined `CSSRuleDefinitionTypeOptions` as an alias for the core [`CustomRuleTypeDefinitions`](https://github.com/eslint/rewrite/blob/core-v0.15.0/packages/core/src/types.ts#L589-L596) type.
* Also upgraded `@eslint/core` to v0.15.
refs eslint/rewrite#177
Related PRs: eslint/eslint#19949, eslint/json#121, eslint/markdown#471
=> refactor: use `CustomRuleDefinitionType` in `CSSRuleDefinition`

src/languages/css-source-code.js
Hi,
In this PR, I've added missing type annotations to variables.
Adding type annotations helps improve type safety, and I noticed that some variables were missing them, so I went ahead and added the necessary annotations.
=> refactor: add missing type annotations to variables

src/rules/no-duplicate-imports.js, tests/rules/no-duplicate-imports.test.js
This pull request adds autofix support to the `no-duplicate-imports` rule. The goal is to allow users to automatically remove duplicate `@import` statements in their CSS files.
- Updated the `no-duplicate-imports` rule to provide an autofix that removes duplicate `@import` statements
- Added and updated tests to verify that autofix works correctly
Fixes #205
=> feat: add autofix to no-duplicate-imports rule

src/rules/no-important.js, tests/rules/no-important.test.js
This pull request enhances the `no-important` rule by providing a suggestion to remove the `!important` flag from CSS declarations.
- Added a suggestion to the `no-important` rule that removes the `!important` flag from CSS declarations.
- Updated the test suite to verify that suggestions are provided and that the output matches the expected code with only the `!important` flag removed.
Fixes #204
=> feat: add suggestion to no-important rule to remove !important flag

src/rules/relative-font-units.js, tests/rules/relative-font-units.test.js
This PR fixes a false positive error in the `relative-font-units` rule where uppercase CSS units like 1REM, 1EM, etc. were being incorrectly flagged as errors. According to the CSS specification, units are case-insensitive, so REM should be equivalent to rem.
- Modified the `relative-font-units` rule to convert the CSS units to lowercase before comparison
- Added test cases to verify case-insensitive unit matching works correctly
Fixes #215
=> fix: make relative-font-units unit matching case-insensitive

package.json, tests/types/types.test.ts
Hi,
This PR is follow-up to https://github.com/eslint/eslint/pull/19995.
You can find more details about this change in https://github.com/eslint/rewrite/issues/234.
- Updated `@eslint/core` to allow arbitrary types for `meta.docs.recommended` in custom rules.
- Upgraded other dependencies to the latest versions.
- Updated type tests.
=> fix: allow any type for `meta.docs.recommended` in custom rules

src/rules/no-invalid-properties.js, tests/rules/no-invalid-properties.test.js
This PR fixes a bug in the `no-invalid-properties` rule where `var()` was matched case-sensitively, causing mixed/uppercase usages like `VAR()` or `Var()` to be missed. CSS function names are ASCII case-insensitive, so these should be treated equivalently.
- Made `var()` detection and fallback parsing case-insensitive
- Added tests for mixed/uppercase `var()` and nested fallbacks
=> fix: make no-invalid-properties var() case-insensitive

docs/rules/use-baseline.md, src/rules/use-baseline.js, tests/rules/use-baseline.test.js
Add new options
- Added `allowAtRules`, `allowProperties`, and `allowSelectors` options
- Added tests and docs
fixes #210
=> feat: add allow-list options for at-rules, properties, and selectors

src/rules/prefer-logical-properties.js
To clean up the `prefer-logical-properties` rule by moving option access (`allowProperties` and `allowUnits`) out of the visitor functions.
Moved the retrieval of `allowProperties` and `allowUnits` from inside the `Declaration` and `Dimension` visitors to the top of the `create` function.
=> refactor: move option access from visitors in prefer-logical-properties

tests/types/tsconfig.json
In this PR, I've added `exactOptionalPropertyTypes` option to type test.
The purpose of adding this option is to prevent the situation happened in https://github.com/eslint/markdown/issues/402 in advance.
FYI, `exactOptionalPropertyTypes` isn't included in strict mode, so it needs to be enabled manually.
https://www.typescriptlang.org/tsconfig/#exactOptionalPropertyTypes
In this PR, I've added `exactOptionalPropertyTypes` option to type test.
Ref: https://github.com/eslint/markdown/issues/402, https://github.com/eslint/markdown/pull/524
N/A
=> test: add `exactOptionalPropertyTypes` option to type test

src/languages/css-source-code.js, tests/types/types.test.ts
I expected the return type of `applyInlineConfig().configs` — specifically `loc.start` and `loc.end` — to include an `offset` property, but they don't. Also `loc.source` is missing.
I expect the types of `loc.start` and `loc.end` to include an `offset` property, and for `loc.source` to be present.
```js
import { CSSSourceCode, CSSLanguage } from "./src/index.js";
const file = {
body: '/* eslint css/no-important: "error" */',
path: "test.css",
};
const language = new CSSLanguage();
const parseResult = language.parse(file);
const cssSourceCode = new CSSSourceCode({
text: file.body,
ast: parseResult.ast,
comments: parseResult.comments,
});
console.log(cssSourceCode.applyInlineConfig().configs[0].loc);
```
If you run the code above, you'll see that …
=> fix: correct the return type of `applyInlineConfig`
